productdetail.content:
  path: 'product-list'
  defaults:
    _controller: 'Drupal\productdetail\Controller\ProductdetailController::getProductList'
    _title: 'List of products'
  requirements:
    _permission: 'access content'
  options:
    no_cache: 'TRUE'

productdetail.admin_settings_form:  
  path: '/admin/config/productdetail/adminsettings'  
  defaults:  
    _form: '\Drupal\productdetail\Form\ProductdetailForm'  
    _title: 'QR Code Block Settings'  
  requirements:  
    _permission: 'access administration pages'  
  options:  
    _admin_route: TRUE